blog/article/urls.py
from django.urls import path

# name of app
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

blog/blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    # url(r'^captcha/', include('captcha.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),

]

blog/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>

    {% include 'header.html' %}

    {% block content %}{% endblock content %}

    {% include 'footer.html' %}

    <script src="{% static 'bootstrap/jquery/jquery-3.6.0.js' %}"></script>

    <script src="{% static 'layer/layer.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

blog/templates/footer.html
{% load static %}
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.zidong.com 2021</p>
    </div>
</footer>

blog/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <a class="navbar-brand" href="#">My Blog</a>

        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">Article</a>
                    <a class="nav-link" href="{% url 'article:article_create' %}">Write Article</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>User Info</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">Delete User</a>
                            <a class="dropdown-item" href='{% url "userprofile:logout" %}'>Log out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">Login</a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %}
                    <form
                            style="display:none;"
                            id="user_delete"
                            action="{% url 'userprofile:delete' user.id %}"
                            method="POST"
                    >
                        {% csrf_token %}
                        <button type="submit">Send</button>
                    </form>
                    <script>
                        function user_delete() {
                            layer.open({
                                title: "Inform Delete",
                                content: "Are you sure to delete user profile?？",
                                yes: function (index, layero) {
                                    $('form#user_delete button').click();
                                    layer.close(index);
                                },
                            })
                        }
                    </script>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>