blog/article/urls.py
from django.urls import path

# name of app
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

blog/blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    # url(r'^captcha/', include('captcha.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [

    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),

]

blog/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


# Blog post data model
class ArticlePost(models.Model):
    # Article author
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # Article title
    title = models.CharField(max_length=100)

    # Article body
    body = models.TextField()

    # Article creation time
    created = models.DateTimeField(default=timezone.now)

    # Article update time
    updated = models.DateTimeField(auto_now=True)

    total_views = models.PositiveIntegerField(default=0)

    class Meta:
        # reverse order
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

blog/article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')

blog/article/views.py
# import markdown
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import HttpResponse
from article.models import ArticlePost
from comment.models import Comment
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.db.models import Q


def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')

    if search:
        if order == 'total_views':

            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:

        search = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()

    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 增加 search 到 context
    context = {'articles': articles, 'order': order, 'search': search}

    return render(request, 'article/list.html', context)


def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    comments = Comment.objects.filter(article=id)
    # article.body = markdown.markdown(article.body,
    #             extensions=[
    #             #'markdown.extensions.extra',
    #             #'markdown.extensions.codehilite',
    #             ])
    article.total_views += 1
    article.save(update_fields=['total_views'])
    context = {'article': article, 'comments': comments}
    return render(request, 'article/detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            new_article.save()
            return redirect("article:article_list")
        else:
            return HttpResponse("The content of the form is incorrect, please fill in again. ")
    else:
        article_post_form = ArticlePostForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', context)


@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):

    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        if request.user != article.author:
            return HttpResponse("Sorry, You can't modify this article")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("Only allow post requests")


@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("Sorry, You can't modify this article")
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("The content of the form is incorrect, please fill in again.")
    else:
        article_post_form = ArticlePostForm()
        context = { 'article': article, 'article_post_form': article_post_form }
        return render(request, 'article/update.html', context)

blog/templates/article/create.html
{% extends "base.html" %} {% load static %}
{% block title %} Write Article {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Article Title</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="body">Article Body</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Done</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/article/detail.html
{% extends "base.html" %}
{% load static %}


{% block title %}
    Article details
{% endblock title %}

{% block content %}



    <div class="container">
        <div class="row">
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-success">
                author：{{ article.author }}
                {% if user == article.author %}
                    · <a href="#" onclick="confirm_safe_delete()">Delete Article</a>
                    · <a href="{% url "article:article_update" article.id %}">Update Article</a>
                {% endif %}
            </div>

            <div class="col-3 mt-4">
                <h4><strong>content</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
        <div class="col-12">
            <p>{{ article.body }}</p>
        </div>

        <hr>
        {% if user.is_authenticated %}
            <div>
                <form
                        action="{% url 'comment:post_comment' article.id %}"
                        method="POST"
                >
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                To Comment：
                            </strong>
                        </label>
                        <textarea
                                type="text"
                                class="form-control"
                                id="body"
                                name="body"
                                rows="2"></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary ">Send</button>
                </form>
            </div>
            <br>
        {% else %}
            <br>
            <h5 class="row justify-content-center">
                Please <a href="{% url 'userprofile:login' %}"> login </a> to reply
            </h5>
            <br>
        {% endif %}



        <h4>Total have {{ comments.count }} comment</h4>
        <div>
            {% for comment in comments %}
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong> at
                    <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> said：
                </p>
                <pre style="font-family: inherit; font-size: 1em;">
{{ comment.body }}</pre>
            {% endfor %}
        </div>
    </div>
    </div>
    </div>

    <form
            style="display:none;"
            id="safe_delete"
            action="{% url 'article:article_safe_delete' article.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">Send</button>
    </form>

    <script>
        function confirm_safe_delete() {
            layer.open({
                title: "Inform to delete",
                content: "Are you sure to delete？",
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>

{% endblock content %}

blog/templates/article/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    front page
{% endblock title %}

{% block content %}

    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}">
                        Latest
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}?order=total_views">
                        Hot
                    </a>
                </li>
            </ol>
        </nav>
        <div class="row">
            <div class="col-auto mr-auto">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text"
                           class="form-control mb-2 mr-sm-2"
                           name="search"
                           placeholder="Search Article..."
                           required
                    >
                </form>
            </div>
        </div>
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}
        <div class="row mt-2">
            {% for article in articles %}
                <div class="col-4 mb-4">
                    <div class="card h-100">
                        <h4 class="card-header">{{ article.title }}</h4>
                        <div class="card-body">
                            <p class="card-text">{{ article.body|slice:'100' }}...</p>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">Read This
                                Article</a>
                            <!-- Total views -->
                            <span>
                                <small class="col align-self-end" style="color: gray;">
                                        Total Views: {{ article.total_views }}
                                </small>
                            </span>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>

    <div class="pagination row">
        <div class="m-auto">
        <span class="step-links">
            {% if articles.has_previous %}
                <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                   class="btn btn-secondary">
            {% endif %}

            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                   class="btn btn-secondary">
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}"
                   class="btn btn-success">
            {% endif %}
        </span>
        </div>
    </div>
{% endblock content %}

blog/templates/article/update.html
{% extends "base.html" %} {% load static %}
{% block title %} Update Article {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Article Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">Article Body</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Done</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}